---
# Source: Workshop-instances/templates/CRB.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user1-argocd-argocd-application-controller
  namespace: user1-application
subjects:
  - kind: ServiceAccount
    name: user1-argocd-argocd-application-controller
    namespace: user1-argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admins
