kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline
  namespace: user12-application
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: user12-argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
