---
# Source: user-template/templates/RB-2.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin
  namespace: user8-argocd
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: user8
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
