---
# Source: user-template/templates/RB-1.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin
  namespace: user5-application
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: user5
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
