---
# Source: Workshop-instances/templates/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: user18-

resources:
  - ../../base
  - namespace.yaml
  - RB-1.yaml
  - RB-2.yaml
  - RB-3.yaml
  - CRB.yaml
  - group.yaml

patches:
  - path: argocd.yaml
  - path: App-Path.yaml
