---
# Source: Workshop-instances/templates/RB-2.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin
  namespace: user18-argocd
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: user18
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
