---
# Source: user-template/templates/CRB.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user11-argocd-argocd-application-controller
  namespace: user11-application
subjects:
  - kind: ServiceAccount
    name: user11-argocd-argocd-application-controller
    namespace: user11-argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admins
